language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - CI=true yarn test --passWithNoTests --ci
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master