matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      addons:
        homebrew:
          packages:
            - wine
            - snapcraft

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn install
  - CI=true yarn test --passWithNoTests --ci
  - yarn build
  - echo \{\"fullNodes\":[\"https://testapla0.apla.io:7079\",\"https://testapla1.apla.io:7079\",\"https://testapla2.apla.io:7079\"]\} > ./build/settings.json
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
      yarn release -ml
      yarn release -w
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
  - echo '<!DOCTYPE html><html><head><meta charset=utf-8><title>Genesis</title><script type="text/javascript">var segmentCount=0;var l=window.location;l.replace(l.protocol+"//"+l.hostname+(l.port?":"+l.port:"")+l.pathname.split("/").slice(0,1+segmentCount).join("/")+"/?p=/"+l.pathname.slice(1).split("/").slice(segmentCount).join("/").replace(/&/g,"~and~")+(l.search?"&q="+l.search.slice(1).replace(/&/g,"~and~"):"")+l.hash);</script></head><body></body></html>' > ./build/404.html

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  fqdn: front.genesis.space
  github-token: $GITHUB_TOKEN
  on:
    branch: master

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"